//! Instalação RESPEITOSA do medidor de janela de uso via statusline (dialeto
//! `UsageWindowSource::ClaudeStatusline`) — SEMPRE por gesto do usuário
//! (botão em Configurações), nunca no boot.
//!
//! As regras do padrão respeitoso (hooks-plan §4 + estudo do Xirp):
//!   1. ENCADEAR, nunca substituir: o comando de statusline vigente (nesta
//!      máquina, o wrapper do Xirp — que por sua vez preserva o do Troco) é
//!      preservado no header do script gerado e re-executado com o MESMO
//!      stdin; o stdout dele continua sendo a statusline do usuário.
//!   2. Script gerado com header "não edite" em diretório NOSSO
//!      (app_data_dir/statusline/); o settings.json só referencia o PATH
//!      estável — o token/porta rotacionam no hook-endpoint.json que o script
//!      lê a cada tick.
//!   3. Backup antes de mexer (`settings.json.bak-mycockpit-<ts>`), JSON por
//!      parse→merge→write atômico, nunca regex.
//!   4. Desinstalação limpa: restaura o VALOR do comando anterior (ou remove
//!      o statusLine se não havia) e apaga o script. Honestidade do claim: a
//!      re-serialização pode mudar formatação e ordem de chaves do arquivo —
//!      `preserve_order` do serde_json foi avaliado e REJEITADO de propósito
//!      (é feature global: mudaria a ordem de todo Map do app e invalidaria
//!      os fingerprints já persistidos do mcp_control, que hasheiam JSON
//!      serializado). O que é garantido é o CONTEÚDO, não os bytes.
//!   4b. Fail-closed onde o efeito é destrutivo: se o slot aponta pro nosso
//!      script mas o script sumiu/perdeu o header (limpador de caches, reset),
//!      instalar/desinstalar ABORTA com erro apontando o backup mais recente —
//!      seguir adiante perderia em silêncio a statusline encadeada (o wrapper
//!      do Xirp, nesta máquina).
//!   5. Fail-open do lado do script: curl com timeout de 1s em background,
//!      erro engolido, `exit 0` sempre — a statusline do usuário NUNCA quebra
//!      nem atrasa porque o app morreu.
//!   6. Só posta o tick que TRAZ `rate_limits` (guarda de substring em shell
//!      puro, padrão do Orca): a statusline tica várias vezes por segundo
//!      durante streaming, mas o rate_limits muda 1x por turno — sem a guarda
//!      o custo do spawn do curl era pago em todo tick. A statusline original
//!      encadeada roda SEMPRE, fora da guarda (ela não pode sumir quando o
//!      payload não tem rate_limits).

use crate::adapters::{capabilities_of, UsageWindowSource};
use serde::Serialize;
use serde_json::{json, Value};
use std::path::PathBuf;
use tauri::{AppHandle, Manager};

const SCRIPT_NAME: &str = "mycockpit-statusline.sh";
const ORIGINAL_MARKER: &str = "# mycockpit-original-command:";

/// Estado da instalação por agent — o que a UI de Configurações mostra,
/// incluindo o PREVIEW exato do que será escrito (transparência antes do
/// gesto) e o comando que será encadeado.
#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct StatuslineStatus {
    /// O slot de statusline aponta pro nosso script?
    pub installed: bool,
    pub settings_path: String,
    pub script_path: String,
    /// O que ocupa o slot HOJE (instalado ou não).
    pub current_command: Option<String>,
    /// O que o nosso script encadeia (só quando instalado).
    pub chained_command: Option<String>,
    /// JSON exato do objeto `statusLine` que a instalação escreverá.
    pub preview: String,
    /// Estado inconsistente detectado (ex.: slot aponta pro nosso script mas
    /// ele sumiu do disco) — a UI mostra; instalar/desinstalar aborta com o
    /// mesmo motivo.
    pub warning: Option<String>,
}

// ---------------------------------------------------------------------------
// Peças PURAS (render do script, parse do header, merge do settings).
// ---------------------------------------------------------------------------

/// Renderiza o script encadeador. `original` = o comando que ocupava o slot
/// (preservado no header E re-executado no fim, padrão do wrapper do Xirp).
pub fn render_script(engine: &str, original: Option<&str>, endpoint_file: &str) -> String {
    let chain = match original {
        Some(cmd) if !cmd.trim().is_empty() => format!(
            "# encadeia a statusline que ocupava o slot (o stdout dela é a sua statusline):\nprintf '%s' \"$input\" | {cmd}\n"
        ),
        _ => "# não havia statusline antes: não imprime nada (o Claude mostra o padrão dele).\n".to_string(),
    };
    format!(
        "#!/bin/bash\n\
         # Generated by MyCockpit — DO NOT EDIT (regenerado a cada instalação)\n\
         # mycockpit-schema: 1\n\
         {ORIGINAL_MARKER} {original}\n\
         # Medidor de janela de uso: envia o stdin da statusline (rate_limits)\n\
         # pro MyCockpit em loopback e repassa pra statusline original acima.\n\
         # Fail-open: app fechado = curl falha em <1s em background e NADA muda\n\
         # na sua statusline. Desinstalação limpa em Configurações do MyCockpit.\n\
         input=$(cat)\n\
         # Só o tick que traz rate_limits interessa (muda 1x por turno); os demais\n\
         # ticks (vários por segundo durante streaming) nem spawnam o curl.\n\
         case \"$input\" in *'\"rate_limits\"'*)\n\
         \x20 ep=\"{endpoint_file}\"\n\
         \x20 if [ -r \"$ep\" ]; then\n\
         \x20   port=$(sed -n 's/.*\"port\":[[:space:]]*\\([0-9]*\\).*/\\1/p' \"$ep\" | head -1)\n\
         \x20   token=$(sed -n 's/.*\"token\":[[:space:]]*\"\\([a-f0-9]*\\)\".*/\\1/p' \"$ep\" | head -1)\n\
         \x20   if [ -n \"$port\" ] && [ -n \"$token\" ]; then\n\
         \x20     printf '%s' \"$input\" | curl -s -X POST \"http://127.0.0.1:${{port}}/hook/{engine}\" \\\n\
         \x20       -H \"Authorization: Bearer ${{token}}\" -H \"Content-Type: application/json\" \\\n\
         \x20       --connect-timeout 1 --max-time 1 --data-binary @- >/dev/null 2>&1 &\n\
         \x20   fi\n\
         \x20 fi\n\
         ;; esac\n\
         {chain}\
         exit 0\n",
        original = original.unwrap_or(""),
    )
}

/// Extrai o comando original do header de um script NOSSO. Vazio/ausente →
/// None (não havia statusline antes da instalação).
pub fn original_from_script(content: &str) -> Option<String> {
    for line in content.lines() {
        if let Some(rest) = line.strip_prefix(ORIGINAL_MARKER) {
            let cmd = rest.trim();
            return (!cmd.is_empty()).then(|| cmd.to_string());
        }
    }
    None
}

/// Comando no slot de statusline do settings (só `type: "command"` tem um).
pub fn current_command(settings: &Value) -> Option<String> {
    let sl = settings.get("statusLine")?;
    sl.get("command")?.as_str().map(str::to_string)
}

/// Settings com o slot apontando pro NOSSO script: preserva todos os outros
/// campos do arquivo E do objeto statusLine (padding etc.), só troca
/// type/command. Nunca regex: parse→merge.
pub fn with_script(settings: &Value, script_path: &str) -> Value {
    let mut out = settings.clone();
    if !out.is_object() {
        out = json!({});
    }
    let mut sl = out
        .get("statusLine")
        .filter(|v| v.is_object())
        .cloned()
        .unwrap_or_else(|| json!({}));
    sl["type"] = json!("command");
    sl["command"] = json!(script_path);
    out["statusLine"] = sl;
    out
}

/// Settings restaurado na desinstalação: `original` volta pro slot; sem
/// original, o objeto statusLine sai inteiro (era ausente antes de nós).
pub fn without_script(settings: &Value, original: Option<&str>) -> Value {
    let mut out = settings.clone();
    match original {
        Some(cmd) => {
            let mut sl = out
                .get("statusLine")
                .filter(|v| v.is_object())
                .cloned()
                .unwrap_or_else(|| json!({}));
            sl["type"] = json!("command");
            sl["command"] = json!(cmd);
            out["statusLine"] = sl;
        }
        None => {
            if let Some(obj) = out.as_object_mut() {
                obj.remove("statusLine");
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Caminhos e IO (dialeto ClaudeStatusline: ~/.claude/settings.json).
// ---------------------------------------------------------------------------

/// Gate de capability: só motor que declara o dialeto de statusline tem
/// instalador — os demais recebem erro honesto, nunca um no-op silencioso.
fn require_statusline(engine: &str) -> Result<(), String> {
    match capabilities_of(engine).and_then(|c| c.usage_window) {
        Some(UsageWindowSource::ClaudeStatusline) => Ok(()),
        _ => Err(format!(
            "{engine} não tem medidor por statusline (capability ausente)"
        )),
    }
}

/// settings.json do dialeto ClaudeStatusline. Respeita CLAUDE_CONFIG_DIR
/// (mesmo contrato do CLI); padrão ~/.claude/settings.json.
fn settings_path() -> Result<PathBuf, String> {
    if let Ok(dir) = std::env::var("CLAUDE_CONFIG_DIR") {
        if !dir.trim().is_empty() {
            return Ok(PathBuf::from(dir).join("settings.json"));
        }
    }
    let home = std::env::var("HOME").map_err(|_| "sem HOME no ambiente".to_string())?;
    Ok(PathBuf::from(home).join(".claude").join("settings.json"))
}

fn script_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_data_dir()
        .map_err(|e| format!("sem app_data_dir: {e}"))?
        .join("statusline")
        .join(SCRIPT_NAME))
}

/// Lê e parseia o settings.json. Ausente → objeto vazio (instalação cria);
/// INVÁLIDO ou JSON válido que NÃO é objeto (`[]`, `null`, string) → erro
/// honesto: nunca sobrescrevemos um arquivo que não entendemos (podia ser um
/// settings quebrado de propósito) — trocar por `{}` apagaria o que quer que
/// aquilo fosse.
fn read_settings(path: &PathBuf) -> Result<Value, String> {
    match std::fs::read_to_string(path) {
        Ok(s) => {
            let v: Value = serde_json::from_str(&s).map_err(|e| {
                format!("{} não parseia como JSON ({e}); nada foi alterado", path.display())
            })?;
            if !v.is_object() {
                return Err(format!(
                    "{} é JSON válido mas não é um objeto; nada foi alterado",
                    path.display()
                ));
            }
            Ok(v)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(json!({})),
        Err(e) => Err(format!("não consegui ler {}: {e}", path.display())),
    }
}

/// Backup `.bak-mycockpit-<ts>` mais recente ao lado do settings (pra
/// mensagem de erro do fail-closed apontar a saída de recuperação).
fn latest_backup(settings: &PathBuf) -> Option<PathBuf> {
    let dir = settings.parent()?;
    let mut best: Option<(u64, PathBuf)> = None;
    for entry in std::fs::read_dir(dir).ok()?.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        let Some(ts) = name.strip_prefix("settings.json.bak-mycockpit-") else {
            continue;
        };
        let Ok(ts) = ts.parse::<u64>() else { continue };
        if best.as_ref().is_none_or(|(b, _)| ts > *b) {
            best = Some((ts, entry.path()));
        }
    }
    best.map(|(_, p)| p)
}

/// Anexa a dica do backup mais recente a um erro de estado inconsistente.
fn with_backup_hint(err: String, settings: &PathBuf) -> String {
    match latest_backup(settings) {
        Some(bak) => format!("{err}. Backup mais recente: {}", bak.display()),
        None => err,
    }
}

/// Backup `settings.json.bak-mycockpit-<ts>` (só se o arquivo existe).
fn backup_settings(path: &PathBuf) -> Result<(), String> {
    if !path.exists() {
        return Ok(());
    }
    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let bak = path.with_file_name(format!("settings.json.bak-mycockpit-{ts}"));
    std::fs::copy(path, &bak).map_err(|e| format!("backup falhou ({e}); nada foi alterado"))?;
    Ok(())
}

fn write_settings(path: &PathBuf, v: &Value) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let body = serde_json::to_string_pretty(v).map_err(|e| e.to_string())?;
    crate::fsx::write_atomic(path, &body)
}

fn write_script(path: &PathBuf, content: &str) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    crate::fsx::write_atomic(path, content)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))
            .map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Comando que instalação/desinstalação devem tratar como "o anterior": o que
/// ocupa o slot hoje — exceto quando o slot já é NOSSO (reinstalação): aí o
/// anterior mora no header do script existente (nunca encadear a nós mesmos).
/// FAIL-CLOSED onde o efeito é destrutivo: slot nosso com script
/// sumido/ilegível ou sem o header = Err — seguir adiante perderia em
/// silêncio a statusline encadeada (ex.: o wrapper do Xirp desta máquina).
/// Header presente mas VAZIO segue sendo Ok(None): é o estado legítimo de
/// quem instalou sem statusline anterior.
fn resolve_original(
    current: Option<String>,
    script: &str,
    existing_script: Option<&str>,
) -> Result<Option<String>, String> {
    match current {
        Some(cmd) if cmd == script => match existing_script {
            None => Err(
                "o slot de statusline aponta pro script do MyCockpit, mas o script sumiu do disco \
                 (limpador de caches?); não dá pra saber qual statusline estava encadeada"
                    .to_string(),
            ),
            Some(content) if !content.lines().any(|l| l.starts_with(ORIGINAL_MARKER)) => Err(
                "o script no lugar do MyCockpit não tem o header esperado; não dá pra saber qual \
                 statusline estava encadeada"
                    .to_string(),
            ),
            Some(content) => Ok(original_from_script(content)),
        },
        other => Ok(other),
    }
}

fn status_of(app: &AppHandle, engine: &str) -> Result<StatuslineStatus, String> {
    require_statusline(engine)?;
    let spath = settings_path()?;
    let script = script_path(app)?;
    let script_str = script.to_string_lossy().to_string();
    let settings = read_settings(&spath)?;
    let current = current_command(&settings);
    let existing_script = std::fs::read_to_string(&script).ok();
    let installed = current.as_deref() == Some(script_str.as_str());
    // status é LEITURA: o estado inconsistente não derruba a consulta, vira
    // `warning` visível (instalar/desinstalar é que abortam com este motivo).
    let (chained, warning) =
        match resolve_original(current.clone(), &script_str, existing_script.as_deref()) {
            Ok(c) => (c, None),
            Err(e) => (None, Some(with_backup_hint(e, &spath))),
        };
    let preview = serde_json::to_string_pretty(
        with_script(&settings, &script_str)
            .get("statusLine")
            .unwrap_or(&Value::Null),
    )
    .map_err(|e| e.to_string())?;
    Ok(StatuslineStatus {
        installed,
        settings_path: spath.to_string_lossy().to_string(),
        script_path: script_str,
        current_command: current,
        chained_command: chained,
        preview,
        warning,
    })
}

// ---------------------------------------------------------------------------
// Comandos (gesto do usuário em Configurações — NUNCA no boot).
// ---------------------------------------------------------------------------

#[tauri::command]
pub fn usage_statusline_status(app: AppHandle, agent: String) -> Result<StatuslineStatus, String> {
    status_of(&app, &agent)
}

/// Instala (ou reinstala, idempotente): gera o script encadeador e aponta o
/// slot pra ele, com backup e preservação do comando anterior.
#[tauri::command]
pub fn usage_statusline_install(app: AppHandle, agent: String) -> Result<StatuslineStatus, String> {
    require_statusline(&agent)?;
    let spath = settings_path()?;
    let script = script_path(&app)?;
    let script_str = script.to_string_lossy().to_string();
    let settings = read_settings(&spath)?;
    let existing_script = std::fs::read_to_string(&script).ok();
    // Fail-closed: slot nosso sem script legível aborta ANTES de escrever
    // qualquer coisa — reinstalar por cima geraria um script SEM o chain e a
    // statusline do usuário (Xirp/Troco) sumiria em silêncio.
    let original = resolve_original(
        current_command(&settings),
        &script_str,
        existing_script.as_deref(),
    )
    .map_err(|e| with_backup_hint(e, &spath))?;
    let endpoint = crate::hook_gateway::endpoint_file(&app)?;
    write_script(
        &script,
        &render_script(&agent, original.as_deref(), &endpoint.to_string_lossy()),
    )?;
    backup_settings(&spath)?;
    write_settings(&spath, &with_script(&settings, &script_str))?;
    log::info!("statusline: medidor instalado pra {agent} (encadeando {original:?})");
    status_of(&app, &agent)
}

/// Desinstala limpo: restaura o comando anterior (ou remove o statusLine se
/// não havia) e apaga o script. O backup da instalação fica no disco.
#[tauri::command]
pub fn usage_statusline_uninstall(
    app: AppHandle,
    agent: String,
) -> Result<StatuslineStatus, String> {
    require_statusline(&agent)?;
    let spath = settings_path()?;
    let script = script_path(&app)?;
    let script_str = script.to_string_lossy().to_string();
    let settings = read_settings(&spath)?;
    // só mexe no slot se ele ainda é NOSSO — o usuário pode ter trocado a
    // statusline depois; aí restaurar o "original" antigo seria regressão.
    if current_command(&settings).as_deref() == Some(script_str.as_str()) {
        // Fail-closed: script sumido/sem header = não dá pra saber o que
        // restaurar; remover o statusLine inteiro apagaria a statusline
        // encadeada (Xirp) em silêncio. Aborta apontando o backup.
        let content = std::fs::read_to_string(&script).ok();
        let original =
            resolve_original(Some(script_str.clone()), &script_str, content.as_deref())
                .map_err(|e| with_backup_hint(e, &spath))?;
        backup_settings(&spath)?;
        write_settings(&spath, &without_script(&settings, original.as_deref()))?;
    }
    if script.exists() {
        std::fs::remove_file(&script).map_err(|e| e.to_string())?;
    }
    log::info!("statusline: medidor desinstalado pra {agent}");
    status_of(&app, &agent)
}

// ---------------------------------------------------------------------------
// Testes — fixtures REAIS desta máquina (12/08/2026): o slot de statusline
// ocupado pelo wrapper do Xirp (que preserva o comando do Troco) é exatamente
// o caso que a regra "encadear, nunca substituir" protege.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Comando REAL que ocupa o slot nesta máquina (wrapper do Xirp).
    const XIRP_WRAPPER: &str = "/Users/viniciusmachado/.claude/xirp-statusline-wrapper.sh";
    const SCRIPT: &str =
        "/Users/x/Library/Application Support/mycockpit/statusline/mycockpit-statusline.sh";
    const ENDPOINT: &str =
        "/Users/x/Library/Application Support/mycockpit/hook-endpoint.json";

    /// Shape REAL do settings.json desta máquina (recortado): statusLine +
    /// vizinhos que NÃO podem ser perdidos no merge.
    fn settings_reais() -> Value {
        json!({
            "$schema": "https://json.schemastore.org/claude-code-settings.json",
            "includeCoAuthoredBy": false,
            "statusLine": { "type": "command", "command": XIRP_WRAPPER },
            "model": "claude-fable-5[1m]"
        })
    }

    #[test]
    fn script_encadeia_o_comando_vigente_e_preserva_no_header() {
        let s = render_script("claude-code", Some(XIRP_WRAPPER), ENDPOINT);
        // o wrapper do Xirp segue rodando com o MESMO stdin (nunca substituir)
        assert!(s.contains(&format!("printf '%s' \"$input\" | {XIRP_WRAPPER}")));
        // e fica preservado no header pra desinstalação restaurar
        assert_eq!(original_from_script(&s).as_deref(), Some(XIRP_WRAPPER));
        // fail-open: timeout de 1s, background, erro engolido, exit 0
        assert!(s.contains("--connect-timeout 1"));
        assert!(s.contains(">/dev/null 2>&1 &"));
        assert!(s.trim_end().ends_with("exit 0"));
        // rota do motor certo no receptor
        assert!(s.contains("/hook/claude-code"));
        // guarda de substring: o bloco do curl só entra em tick com rate_limits
        assert!(s.contains("case \"$input\" in *'\"rate_limits\"'*)"));
        // e o chain fica FORA da guarda (depois do esac): a statusline do
        // usuário roda em todo tick, com ou sem rate_limits.
        let esac = s.find("esac").expect("guarda case/esac no script");
        let chain = s
            .find(&format!("printf '%s' \"$input\" | {XIRP_WRAPPER}"))
            .expect("chain presente");
        assert!(chain > esac, "chain tem que vir depois do esac");
    }

    #[test]
    fn sem_statusline_anterior_o_script_nao_imprime_nada() {
        let s = render_script("claude-code", None, ENDPOINT);
        assert_eq!(original_from_script(&s), None);
        assert!(!s.contains("printf '%s' \"$input\" |  ")); // sem chain vazio
        assert!(s.trim_end().ends_with("exit 0"));
    }

    #[test]
    fn with_script_preserva_o_resto_do_settings() {
        let out = with_script(&settings_reais(), SCRIPT);
        assert_eq!(out["statusLine"]["command"], SCRIPT);
        assert_eq!(out["statusLine"]["type"], "command");
        // vizinhos intactos (o settings.json é do usuário)
        assert_eq!(out["model"], "claude-fable-5[1m]");
        assert_eq!(out["includeCoAuthoredBy"], false);
    }

    #[test]
    fn with_script_preserva_campos_extras_do_proprio_statusline() {
        let mut s = settings_reais();
        s["statusLine"]["padding"] = json!(0);
        let out = with_script(&s, SCRIPT);
        assert_eq!(out["statusLine"]["padding"], 0);
        assert_eq!(out["statusLine"]["command"], SCRIPT);
    }

    #[test]
    fn settings_ausente_instala_do_zero() {
        let out = with_script(&json!({}), SCRIPT);
        assert_eq!(out["statusLine"]["command"], SCRIPT);
    }

    #[test]
    fn desinstalar_restaura_o_valor_do_comando_anterior() {
        // Garantia HONESTA: o CONTEÚDO volta ao que era (igualdade de Value);
        // formatação/ordem de chaves do arquivo podem mudar na re-serialização
        // (preserve_order rejeitado de propósito — ver header do módulo).
        let instalado = with_script(&settings_reais(), SCRIPT);
        let restaurado = without_script(&instalado, Some(XIRP_WRAPPER));
        assert_eq!(restaurado, settings_reais());
    }

    #[test]
    fn desinstalar_sem_original_remove_o_slot_inteiro() {
        let mut sem = settings_reais();
        sem.as_object_mut().unwrap().remove("statusLine");
        let instalado = with_script(&sem, SCRIPT);
        let restaurado = without_script(&instalado, None);
        assert_eq!(restaurado, sem); // volta exatamente ao que era
    }

    #[test]
    fn reinstalar_nunca_encadeia_a_nos_mesmos() {
        // slot já é nosso: o original vem do header do script existente,
        // não do slot (senão o script chamaria a si próprio em loop).
        let existente = render_script("claude-code", Some(XIRP_WRAPPER), ENDPOINT);
        let original = resolve_original(Some(SCRIPT.to_string()), SCRIPT, Some(&existente));
        assert_eq!(original.unwrap().as_deref(), Some(XIRP_WRAPPER));
        // slot de outra pessoa: encadeia o que está lá
        let outro = resolve_original(Some(XIRP_WRAPPER.to_string()), SCRIPT, None);
        assert_eq!(outro.unwrap().as_deref(), Some(XIRP_WRAPPER));
        // slot vazio: nada a encadear
        assert_eq!(resolve_original(None, SCRIPT, None), Ok(None));
    }

    #[test]
    fn slot_nosso_com_script_sumido_aborta_em_vez_de_perder_o_encadeado() {
        // Cenário do revisor: limpador de caches apagou o script do
        // app_data_dir, mas o settings ainda aponta pra ele. Seguir adiante
        // desinstalaria o statusLine INTEIRO (o wrapper do Xirp sumiria) ou
        // reinstalaria sem chain — os dois em silêncio. Tem que abortar.
        let r = resolve_original(Some(SCRIPT.to_string()), SCRIPT, None);
        let err = r.unwrap_err();
        assert!(err.contains("sumiu do disco"), "mensagem honesta: {err}");
    }

    #[test]
    fn slot_nosso_com_script_sem_header_aborta() {
        // Arquivo no lugar do nosso script mas sem o header (editado/trocado):
        // não dá pra afirmar qual statusline estava encadeada — aborta.
        let r = resolve_original(
            Some(SCRIPT.to_string()),
            SCRIPT,
            Some("#!/bin/bash\necho outra coisa\n"),
        );
        let err = r.unwrap_err();
        assert!(err.contains("header"), "mensagem honesta: {err}");
        // header presente mas VAZIO segue válido: instalado sem statusline
        // anterior é estado legítimo, não corrupção.
        let vazio = render_script("claude-code", None, ENDPOINT);
        assert_eq!(
            resolve_original(Some(SCRIPT.to_string()), SCRIPT, Some(&vazio)),
            Ok(None)
        );
    }

    #[test]
    fn settings_json_valido_mas_nao_objeto_aborta() {
        // `[]`/`null` parseiam como JSON: trocar por {} apagaria o que quer
        // que aquilo fosse — erro honesto, nada alterado.
        let dir = std::env::temp_dir().join(format!("mc-sl-settings-{}", std::process::id()));
        // parte de dir LIMPO: a limpeza do fim não roda se o teste entrar em
        // pânico, e o pid é reciclado pelo SO — sobra de rodada antiga entrava
        // aqui dentro.
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("settings.json");
        for corpo in ["[]", "null", "\"texto\""] {
            std::fs::write(&p, corpo).unwrap();
            let err = read_settings(&p).unwrap_err();
            assert!(err.contains("não é um objeto"), "{corpo}: {err}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn backup_mais_recente_por_timestamp() {
        let dir = std::env::temp_dir().join(format!("mc-sl-bak-{}", std::process::id()));
        // este é o mais exposto do arquivo: ENUMERA o diretório e afirma qual
        // backup é o mais novo. Um `bak-mycockpit-<n>` órfão com n > 200,
        // deixado por rodada que morreu antes da limpeza (pid reciclado),
        // inverteria a asserção. Parte de dir limpo.
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let settings = dir.join("settings.json");
        std::fs::write(dir.join("settings.json.bak-mycockpit-100"), "{}").unwrap();
        std::fs::write(dir.join("settings.json.bak-mycockpit-200"), "{}").unwrap();
        std::fs::write(dir.join("settings.json.bak-outro-999"), "{}").unwrap(); // de outra ferramenta: ignora
        let bak = latest_backup(&settings).unwrap();
        assert!(bak.to_string_lossy().ends_with("bak-mycockpit-200"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn gate_por_capability_nunca_por_nome() {
        assert!(require_statusline("claude-code").is_ok());
        assert!(require_statusline("codex").is_err()); // fonte é RPC, não statusline
        assert!(require_statusline("agy").is_err());
        assert!(require_statusline("motor-inventado").is_err());
    }
}

#[cfg(test)]
mod tests_shell {
    use super::*;

    /// Prova de shell REAL: o script gerado passa no bash -n e, com um
    /// endpoint fake + statusline original fake + um `curl` FAKE na frente do
    /// PATH (que registra a invocação num log), prova as duas pontas da
    /// guarda de rate_limits: (a) tick SEM rate_limits não spawna curl MAS a
    /// statusline original roda; (b) tick COM rate_limits posta. Roda só em
    /// unix (bash presente).
    ///
    /// FLAKE JÁ CORRIGIDO (não regrida) — o teste falhava sob `cargo test`
    /// paralelo e passava com `--test-threads=1`. A causa NÃO era PATH global
    /// nem tmp compartilhado: era LEITURA DE REGISTRO PELA METADE. O curl fake
    /// gravava em DOIS passos (`printf` dos args, depois `cat` do corpo) e a
    /// espera parava no primeiro instante em que o log ficava NÃO-VAZIO. Com a
    /// máquina carregada, o `cat` era desagendado entre os dois appends e o
    /// teste lia só os args: a asserção da URL passava e a do CORPO estourava
    /// (o panic em `logged.contains("rate_limits")`). Paralelismo só alargava
    /// a janela. Correções: (1) o curl fake publica o registro INTEIRO com um
    /// único `mv` (rename é atômico no POSIX — meio registro nunca é visível);
    /// (2) a espera exige o TERMINADOR do registro, não "arquivo não vazio";
    /// (3) diretório e PATH do filho são fixos e exclusivos deste teste.
    #[test]
    #[cfg(unix)]
    fn script_gerado_roda_de_verdade() {
        use std::os::unix::fs::PermissionsExt;
        // Diretório exclusivo deste teste: pid + nanos (dois binários de teste
        // rodando junto, ou um rerun por cima de um tmp órfão, nunca colidem).
        let unico = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir =
            std::env::temp_dir().join(format!("mc-statusline-test-{}-{unico}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let ep = dir.join("hook-endpoint.json");
        std::fs::write(&ep, r#"{"port":1,"token":"abc123","startedAt":0}"#).unwrap();
        let original = dir.join("original.sh");
        std::fs::write(&original, "#!/bin/bash\ncat >/dev/null\necho 'statusline original'\n").unwrap();
        std::fs::set_permissions(&original, std::fs::Permissions::from_mode(0o755)).unwrap();
        // curl fake: anota args + corpo (stdin) no log e sai 0 — é a evidência
        // de que o script decidiu postar. Monta o registro INTEIRO num arquivo
        // parcial e publica com `mv`: o rename é atômico, então o log ou não
        // existe ou já tem args E corpo — nunca metade (era essa a fonte do
        // flake). `FIM-DO-REGISTRO` é o terminador que a espera exige.
        let curl_log = dir.join("curl-log");
        let fake_curl = dir.join("curl");
        std::fs::write(
            &fake_curl,
            format!(
                "#!/bin/bash\n\
                 corpo=$(cat)\n\
                 printf '%s | %s | FIM-DO-REGISTRO' \"$*\" \"$corpo\" > \"{log}.parcial\"\n\
                 mv \"{log}.parcial\" \"{log}\"\n\
                 exit 0\n",
                log = curl_log.display()
            ),
        )
        .unwrap();
        std::fs::set_permissions(&fake_curl, std::fs::Permissions::from_mode(0o755)).unwrap();
        let script = dir.join("mycockpit-statusline.sh");
        std::fs::write(
            &script,
            render_script(
                "claude-code",
                Some(&original.to_string_lossy()),
                &ep.to_string_lossy(),
            ),
        )
        .unwrap();
        // bash -n: sintaxe válida
        let syn = std::process::Command::new("bash")
            .arg("-n")
            .arg(&script)
            .output()
            .unwrap();
        assert!(syn.status.success(), "bash -n falhou: {}", String::from_utf8_lossy(&syn.stderr));

        // PATH do FILHO (nunca `set_var`: variável de ambiente é global do
        // processo e vazaria pras outras threads de teste). Fixo e mínimo — o
        // dir do curl fake na frente, mais os dirs de sistema do que o script
        // usa (sed/head/cat). Não herda o PATH do processo justamente pra não
        // depender de estado global que outro teste possa mexer.
        let path_env = format!("{}:/usr/bin:/bin", dir.display());
        let run = |input: &[u8]| {
            std::process::Command::new("bash")
                .arg(&script)
                .env("PATH", &path_env)
                .stdin(std::process::Stdio::piped())
                .stdout(std::process::Stdio::piped())
                .stderr(std::process::Stdio::piped())
                .spawn()
                .and_then(|mut c| {
                    use std::io::Write;
                    c.stdin.take().unwrap().write_all(input).unwrap();
                    c.wait_with_output()
                })
                .unwrap()
        };

        // (a) tick de streaming SEM rate_limits: nenhum curl spawnado, mas a
        // statusline original roda com o mesmo stdin (o chain fica FORA da
        // guarda — a statusline do usuário nunca some).
        let out = run(b"{\"model\":{\"id\":\"claude-opus-5\"},\"cost\":{\"total_lines_added\":3}}");
        assert!(out.status.success(), "script saiu com erro");
        assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "statusline original");
        std::thread::sleep(std::time::Duration::from_millis(300));
        // nem o log publicado nem o parcial: o curl fake toca os dois, então
        // pegamos o spawn indevido mesmo se ele não tiver chegado no `mv`.
        assert!(
            !curl_log.exists() && !curl_log.with_extension("parcial").exists(),
            "tick sem rate_limits não pode spawnar curl: {}",
            std::fs::read_to_string(&curl_log).unwrap_or_default()
        );

        // (b) tick COM rate_limits: posta (curl fake registra a invocação em
        // background — espera com timeout, sem flake).
        let out = run(b"{\"rate_limits\":{\"primary_used_pct\":23}}");
        assert!(out.status.success(), "script saiu com erro");
        assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "statusline original");
        // Espera o registro COMPLETO (terminador presente), não "log não
        // vazio": ler no meio da gravação era o flake. Orçamento generoso
        // porque a máquina pode estar carregada; sai no primeiro sucesso.
        let mut logged = String::new();
        for _ in 0..200 {
            if let Ok(s) = std::fs::read_to_string(&curl_log) {
                if s.contains("FIM-DO-REGISTRO") {
                    logged = s;
                    break;
                }
            }
            std::thread::sleep(std::time::Duration::from_millis(50));
        }
        assert!(
            logged.contains("/hook/claude-code"),
            "tick com rate_limits tinha que postar pro receptor: {logged:?}"
        );
        assert!(
            logged.contains("rate_limits"),
            "o corpo postado leva o payload da statusline: {logged:?}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
